# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [1]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(a, b, c, d, e)

False True True True False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
a_1 = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
b_1 = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
c_1 = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
d_1 = ['a',1,True,'b',0,False] > ['a',True,1]
e_1 = ['a',1,True,'b',0,False] == 1
f_1 = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print(a_1, b_1, c_1, d_1, e_1, f_1)

False True False True False True

In [3]:
a_1 = ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
b_1 = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
c_1 = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
d_1 = ['a',1,True,'b',0,False] <= ['a',True,1]
e_1 = ['a',1,True,'b',0,False] != 1
f_1 = ['a',True,1] <= ['a',True,1] >= ['a',1,True,'b',0,False]

print(a_1, b_1, c_1, d_1, e_1, f_1)

True False True False True False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [4]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('lista_7_df.csv', index_col= 'Unnamed: 0').round(3)
df

         Primeira   Segunda  Terceira    Quarta    Média
Linha 1     2.600     2.800    34.729     0.069   10.050
Linha 2     0.139     6.760     7.840  1206.074  305.203
Linha 3     0.005     0.019     2.600     2.800    1.356
Linha 4    34.729     0.069     0.139     6.760   10.424
Linha 5     7.840  1206.074     0.005     0.019  303.484
Média       9.062   243.144     9.062   243.144  126.103

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [12]:
df_array = np.ones((6,5), dtype=int)
df_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [13]:
df == df_array

         Primeira  Segunda  Terceira  Quarta  Média
Linha 1     False    False     False   False  False
Linha 2     False    False     False   False  False
Linha 3     False    False     False   False  False
Linha 4     False    False     False   False  False
Linha 5     False    False     False   False  False
Média       False    False     False   False  False

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [14]:
df >= df_array

         Primeira  Segunda  Terceira  Quarta  Média
Linha 1      True     True      True   False   True
Linha 2     False     True      True    True   True
Linha 3     False    False      True    True   True
Linha 4      True    False     False    True   True
Linha 5      True     True     False   False   True
Média        True     True      True    True   True

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [15]:
df <= df_array

         Primeira  Segunda  Terceira  Quarta  Média
Linha 1     False    False     False    True  False
Linha 2      True    False     False   False  False
Linha 3      True     True     False   False  False
Linha 4     False     True      True   False  False
Linha 5     False    False      True    True  False
Média       False    False     False   False  False

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [17]:
df <= (0 < 1)

         Primeira  Segunda  Terceira  Quarta  Média
Linha 1     False    False     False    True  False
Linha 2      True    False     False   False  False
Linha 3      True     True     False   False  False
Linha 4     False     True      True   False  False
Linha 5     False    False      True    True  False
Média       False    False     False   False  False

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [26]:
teste = df ['Média'] < 5
teste

Linha 1    False
Linha 2    False
Linha 3     True
Linha 4    False
Linha 5    False
Média      False
Name: Média, dtype: bool

In [21]:
teste_conv = list(teste)
teste_conv

[False, False, True, False, False, False]

In [25]:
quantidade = teste_conv.count(True)
quantidade

1

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [27]:
teste2 = df ['Média'] > 5
teste2

Linha 1     True
Linha 2     True
Linha 3    False
Linha 4     True
Linha 5     True
Média       True
Name: Média, dtype: bool

In [28]:
teste2_conv = list(teste2)
teste2_conv

[True, True, False, True, True, True]

In [29]:
quantidade2 = teste2_conv.count(True)
quantidade2

5