In [1]:
import pandas as pd
import numpy as np

In [2]:
obj_array = np.random.normal(20, 2.5, 40).reshape(8,5)
obj_array

array([[20.74405157, 15.61439179, 14.88028437, 17.16325013, 20.43383228],
       [23.44904221, 23.56820306, 14.21477802, 20.19206671, 21.46787529],
       [19.18304511, 23.42062083, 20.23523357, 23.02771392, 15.76083247],
       [20.97231924, 15.42663927, 18.98711451, 17.65914185, 20.32661684],
       [21.37089434, 15.599028  , 17.37859671, 18.84515599, 20.05285718],
       [21.45559408, 24.13834343, 21.6174042 , 16.34808151, 19.62628818],
       [22.7524396 , 22.00548445, 24.25095367, 18.13425222, 20.4032297 ],
       [24.71989745, 22.00639925, 24.39220326, 16.60700001, 19.76476456]])

In [4]:
if obj_array[3,1] >= 200:
    resposta = f"Gene analisado é superior a 200 => {obj_array[3,1]}"
elif obj_array[3,1] < 10:
    resposta = f"Gene analisado é inferior a 10 => {obj_array[3,1]}"
else:
    resposta = f"Gene analisado está entre 10 e 200 => {obj_array[3,1]}"

In [5]:
resposta

'Gene analisado está entre 10 e 200 => 20.403708635345836'

In [38]:
if np.all(obj_array > 22):
    print("Valores no objeto são superiores a 22")
else:
    print("Alguns dos valores no obj não são superiores a 22")

Alguns dos valores no obj não são superiores a 22

In [39]:
obj_data = pd.DataFrame(obj_array)
obj_data

           0          1          2          3          4
0  23.522853  20.578586  16.412767  21.323582  23.614313
1  22.470482  23.355577  17.093368  23.259667  20.598833
2  17.900556  21.594792  19.423031  17.634765  17.641189
3  19.257342  20.829334  17.174836  20.072257  19.833274
4  22.274898  15.172053  20.592204  20.309297  19.947800
5  24.684448  18.753449  19.016860  19.524147  18.066861
6  22.300866  19.911540  20.513400  19.387917  19.092066
7  24.379958  21.242793  20.344690  22.630761  22.205386

In [40]:
if np.all(obj_data > 22):
    print("Valores no objeto são superiores a 22")
else:
    print("Alguns dos valores no obj não são superiores a 22")

Alguns dos valores no obj não são superiores a 22

In [43]:
np.all(obj_data[(obj_data > 22) & (obj_data < 24)])

           0          1   2          3          4
0  23.522853        NaN NaN        NaN  23.614313
1  22.470482  23.355577 NaN  23.259667        NaN
2        NaN        NaN NaN        NaN        NaN
3        NaN        NaN NaN        NaN        NaN
4  22.274898        NaN NaN        NaN        NaN
5        NaN        NaN NaN        NaN        NaN
6  22.300866        NaN NaN        NaN        NaN
7        NaN        NaN NaN  22.630761  22.205386