In [1]:
1 == 1

True

In [1]:
'1' in '[1, 2, 3]'

True

In [3]:
p = 1 
q = True

p is q

False

In [3]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
})
display(df)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
display(df)
df.mean(axis="index") # axis= index pega todas as linhas de uma coluna para fazer a média, axis=columns pega todas as colunas de uma linha para fazer a média

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

a    2.0
b    5.0
c    8.0
dtype: float64

In [11]:
df.rename(
    columns={'a': 'coluna_a', 
             'b': 'coluna_b', 
             'c': 'coluna_c'
            },
    inplace=True
)
df

   coluna_a  coluna_b  coluna_c
0         1         4         7
1         2         5         8
2         3         6         9